insert into donators (email)
values ('1@com'),
       ('2@com'),
       ('3@com'),
       ('4@com'),
       ('5@com'),
       ('6@com'),
       ('7@com'),
       ('8@com'),
       ('9@com'),
       ('10@com'),
       ('11@com'),
       ('12@com'),
       ('13@com'),
       ('14@com'),
       ('15@com'),
       ('16@com'),
       ('17@com'),
       ('18@com'),
       ('19@com'),
       ('20@com')